import "./globals.css";

import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Sidebar } from "@/components/Sidbar";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Tech News Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <div className="flex container mx-auto">
          <div className="h-svh md:block w-[300px]">
            <Sidebar />
          </div>
          <div className="p-5 w-full md:max-w-[1114px]">{children}</div>
        </div>
      </body>
    </html>
  );
}
